### ISSUE TITLE
version  1.2.5.3 on pypi?

### ISSUE THREAD

**Issue by sudomain** [drshajul/termux-api#16]
Hello,

First, thank you for this package, it's very useful to me. Why is there a version 1.2.5.3 on pypi? The last commit in this repo indicates version 1.2.5.2

**Comment by drshajul** [comment]
Now it is up-to-date. I forgot to push!

**Comment by sudomain** [comment]
Thank you! A bit off-topic but, by any chance, would you happen to know why your package's `termux.UI.speech()` works perfectly, but my shell command `termux-speech-to-text` doesn't work at all? I presume your package wraps around this and does something to fix it?
